### ISSUE TITLE
Rules generated for links are too specific

### ISSUE THREAD

**Issue by markhowellsmead** [m-e-h/postcss-editor-styles#2]
Using this to compile CSS for the editor and frontend, the styles for links in the editor are too specific to override. A simplified example:

## SCSS
```scss
a {
	color: red;
}

h1 {
	color: black;
	a {
		color: currentColor;
	}
}
```

This generates the following CSS rules for the editor:

## CSS
```css
.editor-styles-wrapper a:not([class^="components-"]):not([class^="editor-"]):not([class^="block-"]):not([aria-owns]):not([id^="mceu_"]), .editor-styles-wrapper button:not([class^="components-"]):not([class^="editor-"]):not([class^="block-"]):not([aria-owns]):not([id^="mceu_"]) {color: red;}

h1 {color: black;}
h1 a {color: currentColor;}
```

The generated rule for the link tag is _very_ specific and overrides the rule for the `h1 a`. Links both inside and outside the `h1` are red.
